services:
  - type: web
    name: proyectoGIU
    runtime: php
    buildCommand: |
      composer install --no-dev
      npm install && npm run build
      php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
